[[plugins]]
repository = 'Shougo/neobundle.vim'

[[plugins]]
repository = 'Shougo/vimproc'

  [plugins.build]
  windows = 'make -f make_mingw32.mak'
  cygwin = 'make -f make_cygwin.mak'
  mac = 'make -f make_mac.mak'
  unix' = 'make -f make_unix.mak'


[[plugins]]
repository =  'Shougo/vimshell'
